In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('Fish.csv')
dataset

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
5     Bream   450.0     26.8     29.7     34.7  13.6024  4.9274
6     Bream   500.0     26.8     29.7     34.5  14.1795  5.2785
7     Bream   390.0     27.6     30.0     35.0  12.6700  4.6900
8     Bream   450.0     27.6     30.0     35.1  14.0049  4.8438
9     Bream   500.0     28.5     30.7     36.2  14.2266  4.9594
10    Bream   475.0     28.4     31.0     36.2  14.2628  5.1042
11    Bream   500.0     28.7     31.0     36.2  14.3714  4.8146
12    Bream   500.0     29.1     31.5     36.4  13.7592  4.3680
13    Bream   340.0     29.5     32.0     37.3  13.9129  5.0728
14    Bream   600.0     29.4     32.0     37.2  14.9544  5.1708
15    Bream   600.0     29.4     32.0     37.2  15.4380  5.5800
16    Bream   700.0     30.4     33.0     38.3  14.8604  5.2854
17    Bream   700.0     30.4     33.0     38.5  14.9380  5.1975
18    Bream   610.0     30.9     33.5     38.6  15.6330  5.1338
19    Bream   650.0     31.0     33.5     38.7  14.4738  5.7276
20    Bream   575.0     31.3     34.0     39.5  15.1285  5.5695
21    Bream   685.0     31.4     34.0     39.2  15.9936  5.3704
22    Bream   620.0     31.5     34.5     39.7  15.5227  5.2801
23    Bream   680.0     31.8     35.0     40.6  15.4686  6.1306
24    Bream   700.0     31.9     35.0     40.5  16.2405  5.5890
25    Bream   725.0     31.8     35.0     40.9  16.3600  6.0532
26    Bream   720.0     32.0     35.0     40.6  16.3618  6.0900
27    Bream   714.0     32.7     36.0     41.5  16.5170  5.8515
28    Bream   850.0     32.8     36.0     41.6  16.8896  6.1984
29    Bream  1000.0     33.5     37.0     42.6  18.9570  6.6030
..      ...     ...      ...      ...      ...      ...     ...
129    Pike   300.0     31.7     34.0     37.8   5.7078  4.1580
130    Pike   300.0     32.7     35.0     38.8   5.9364  4.3844
131    Pike   300.0     34.8     37.3     39.8   6.2884  4.0198
132    Pike   430.0     35.5     38.0     40.5   7.2900  4.5765
133    Pike   345.0     36.0     38.5     41.0   6.3960  3.9770
134    Pike   456.0     40.0     42.5     45.5   7.2800  4.3225
135    Pike   510.0     40.0     42.5     45.5   6.8250  4.4590
136    Pike   540.0     40.1     43.0     45.8   7.7860  5.1296
137    Pike   500.0     42.0     45.0     48.0   6.9600  4.8960
138    Pike   567.0     43.2     46.0     48.7   7.7920  4.8700
139    Pike   770.0     44.8     48.0     51.2   7.6800  5.3760
140    Pike   950.0     48.3     51.7     55.1   8.9262  6.1712
141    Pike  1250.0     52.0     56.0     59.7  10.6863  6.9849
142    Pike  1600.0     56.0     60.0     64.0   9.6000  6.1440
143    Pike  1550.0     56.0     60.0     64.0   9.6000  6.1440
144    Pike  1650.0     59.0     63.4     68.0  10.8120  7.4800
145   Smelt     6.7      9.3      9.8     10.8   1.7388  1.0476
146   Smelt     7.5     10.0     10.5     11.6   1.9720  1.1600
147   Smelt     7.0     10.1     10.6     11.6   1.7284  1.1484
148   Smelt     9.7     10.4     11.0     12.0   2.1960  1.3800
149   Smelt     9.8     10.7     11.2     12.4   2.0832  1.2772
150   Smelt     8.7     10.8     11.3     12.6   1.9782  1.2852
151   Smelt    10.0     11.3     11.8     13.1   2.2139  1.2838
152   Smelt     9.9     11.3     11.8     13.1   2.2139  1.1659
153   Smelt     9.8     11.4     12.0     13.2   2.2044  1.1484
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [3]:
O = dataset.iloc[:,0]
O

0      Bream
1      Bream
2      Bream
3      Bream
4      Bream
5      Bream
6      Bream
7      Bream
8      Bream
9      Bream
10     Bream
11     Bream
12     Bream
13     Bream
14     Bream
15     Bream
16     Bream
17     Bream
18     Bream
19     Bream
20     Bream
21     Bream
22     Bream
23     Bream
24     Bream
25     Bream
26     Bream
27     Bream
28     Bream
29     Bream
       ...  
129     Pike
130     Pike
131     Pike
132     Pike
133     Pike
134     Pike
135     Pike
136     Pike
137     Pike
138     Pike
139     Pike
140     Pike
141     Pike
142     Pike
143     Pike
144     Pike
145    Smelt
146    Smelt
147    Smelt
148    Smelt
149    Smelt
150    Smelt
151    Smelt
152    Smelt
153    Smelt
154    Smelt
155    Smelt
156    Smelt
157    Smelt
158    Smelt
Name: Species, Length: 159, dtype: object

In [4]:
dataset['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [5]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [6]:
x = dataset.iloc[:,[0,2,3,4,5,6]].values

In [7]:
y = dataset.iloc[:,1].values

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()

ct=ColumnTransformer([('oh',OneHotEncoder(),[0])],remainder='passthrough')

In [9]:
x = ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 30.0, 11.52, 4.02],
       [1.0, 0.0, 0.0, ..., 31.2, 12.48, 4.3056],
       [1.0, 0.0, 0.0, ..., 31.1, 12.3778, 4.6961],
       ...,
       [0.0, 0.0, 0.0, ..., 13.8, 2.2769999999999997, 1.2558],
       [0.0, 0.0, 0.0, ..., 15.2, 2.8728, 2.0672],
       [0.0, 0.0, 0.0, ..., 16.2, 2.9322, 1.8792]], dtype=object)

In [10]:
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
      

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10000)

In [12]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
ypred = mlr.predict(x_test)


In [14]:
ypred

array([ 718.06721366,  712.57810095,  887.30510826, 1426.75279735,
        680.85725697,  808.42966591,  168.09223184,  108.83912825,
        185.2044695 ,  237.6374358 ,  430.72122646,  258.63583313,
        115.92678652,  196.37995379,  861.38826403,  413.7019005 ,
         32.64882712,  944.28168493,  131.0688483 ,  720.72605822,
        626.05939662,  989.39507303,  634.06562714,  536.43981038,
        -10.76055962,  204.11508289,  982.51619746,  482.74166561,
        956.105739  ,  257.18803764,   10.78276011,  859.36964596])

In [15]:
y_test

array([ 690. ,  700. ,  925. , 1650. ,  620. ,  650. ,  170. ,   19.7,
        130. ,  145. ,  345. ,  169. ,  120. ,  150. ,  920. ,  306. ,
         90. , 1100. ,  125. ,  800. ,  556. , 1000. ,  840. ,  500. ,
          8.7,  161. , 1000. ,  450. , 1100. ,  180. ,   69. ,  955. ])

In [16]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [17]:
accuracy

0.9381871771286757

In [18]:
test = [["Bream",30,30,30,10,5]]
y = ct.transform(test)

In [19]:
y

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30, 30, 30, 10, 5]],
      dtype=object)

In [20]:
a = mlr.predict(y)

In [21]:
a

array([161.1128824])

In [22]:
test_2 = [["Pike",24.2,26.4,31.0,12.4800,4.3056]]
y2 = ct.transform(test_2)

In [23]:
y2

array([[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 24.2, 26.4, 31.0, 12.48,
        4.3056]], dtype=object)

In [24]:
b = mlr.predict(y2)

In [25]:
b


array([104.77180723])